### ISSUE TITLE
Optimizing SubResourceReference 

### ISSUE THREAD

**Issue by AmitBarr** [knutaa/apicore#1]
Hello, 
I enjoy using this tool, however I find that generating diagrams with more then 20 entities can make the diagram hard to read.
I use the "subResourceConfig" to generate more SubResourceReference which create successful results.
However I think that the next suggestions can make the diagram more optimized:
1.   Allow having configuration to generate every SubResourceReference the without any properties, users can view the SubResourceReference properties on the SubResource own diagram. 
2. "subResourceConfig" is not working for entitles which are not "isolated" and are pointing to an entity which has other entities pointing to it.  Example A is pointing to B & C and B is pointing to C. If i added B to subResourceConfig under A it will not be generated as a sub-resource as A is pointing to it. I suggest allowing B to be separated to another SubResourceReference having C included in both diagrams. 

Thanks a lot,
Amit

**Comment by knutaa** [comment]
Hi, good suggestions!

For the first one, try the new property


    "showSubResourceProperties": false

This is currently default for version 2.5.2: https://github.com/knutaa/oas2puml/packages/781389

Result like this:

[cid:80cc84a6-e97d-4cbf-9d8f-f8cee573d4b2]

The second suggestion is a bit more work...

Br,
Knut







________________________________
Fra: AmitBarr ***@***.***>
Sendt: torsdag 3. mars 2022 16:01
Til: knutaa/apicore ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [knutaa/apicore] Optimizing SubResourceReference (Issue #1)


Hello,
I enjoy using this tool, however I find that generating diagrams with more then 20 entities can make the diagram hard to read.
I use the "subResourceConfig" to generate more SubResourceReference which create successful results.
However I think that the next suggestions can make the diagram more optimized:

  1.  Allow having configuration to generate every SubResourceReference the without any properties, users can view the SubResourceReference properties on the SubResource own diagram.
  2.  "subResourceConfig" is not working for entitles which are not "isolated" and are pointing to an entity which has other entities pointing to it. Example A is pointing to B & C and B is pointing to C. If i added B to subResourceConfig under A it will not be generated as a sub-resource as A is pointing to it. I suggest allowing B to be separated to another SubResourceReference having C included in both diagrams.

Thanks a lot,
Amit

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fknutaa%2Fapicore%2Fissues%2F1&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TMOukN1uhPVcnmQsYu2DoFRwWjsAW6anvpEF2rI1xuU%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFMSDVZFSUKYNYC7LSM3J4TU6DH6JANCNFSM5P2XJFVQ&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WOMiKjYJndDdj%2BfL%2BG%2FQ0LxiMZ%2B%2B%2FvC2GFzVElyIkG8%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


Sensitivity: Internal

**Comment by knutaa** [comment]
Hi, regarding the second proposal, would be good with a specific example.

This seems to work:


    "subResourceConfig": {

"ShoppingCart": [ "ShoppingCart" , "Product", "Validation" ]

},

I.e. a separate diagram is generated for Validation (C) that is used by ShoppingCart (A) and Product (B).

Your specific example would be useful.

Thanks,
Knut

________________________________
Fra: Knut Johannessen ***@***.***>
Sendt: torsdag 3. mars 2022 23:40
Til: knutaa/apicore ***@***.***>
Emne: Sv: [knutaa/apicore] Optimizing SubResourceReference (Issue #1)

Hi, good suggestions!

For the first one, try the new property


    "showSubResourceProperties": false

This is currently default for version 2.5.2: https://github.com/knutaa/oas2puml/packages/781389

Result like this:

[cid:80cc84a6-e97d-4cbf-9d8f-f8cee573d4b2]

The second suggestion is a bit more work...

Br,
Knut







________________________________
Fra: AmitBarr ***@***.***>
Sendt: torsdag 3. mars 2022 16:01
Til: knutaa/apicore ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [knutaa/apicore] Optimizing SubResourceReference (Issue #1)


Hello,
I enjoy using this tool, however I find that generating diagrams with more then 20 entities can make the diagram hard to read.
I use the "subResourceConfig" to generate more SubResourceReference which create successful results.
However I think that the next suggestions can make the diagram more optimized:

  1.  Allow having configuration to generate every SubResourceReference the without any properties, users can view the SubResourceReference properties on the SubResource own diagram.
  2.  "subResourceConfig" is not working for entitles which are not "isolated" and are pointing to an entity which has other entities pointing to it. Example A is pointing to B & C and B is pointing to C. If i added B to subResourceConfig under A it will not be generated as a sub-resource as A is pointing to it. I suggest allowing B to be separated to another SubResourceReference having C included in both diagrams.

Thanks a lot,
Amit

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fknutaa%2Fapicore%2Fissues%2F1&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TMOukN1uhPVcnmQsYu2DoFRwWjsAW6anvpEF2rI1xuU%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFMSDVZFSUKYNYC7LSM3J4TU6DH6JANCNFSM5P2XJFVQ&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WOMiKjYJndDdj%2BfL%2BG%2FQ0LxiMZ%2B%2B%2FvC2GFzVElyIkG8%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


Sensitivity: Internal

**Comment by AmitBarr** [comment]
> 

Thanks Knut, that is excellent, it will be much help. BTW, I tried to do the change myself over the weekend, but it was not that elegant. I really need to brush up on my development skills.  Thanks again. Amit

**Comment by AmitBarr** [comment]
> Hi, regarding the second proposal, would be good with a specific example. This seems to work: "subResourceConfig": { "ShoppingCart": [ "ShoppingCart" , "Product", "Validation" ] }, I.e. a separate diagram is generated for Validation (C) that is used by ShoppingCart (A) and Product (B). Your specific example would be useful. Thanks, Knut
> […](#)
> ________________________________ Fra: Knut Johannessen ***@***.***> Sendt: torsdag 3. mars 2022 23:40 Til: knutaa/apicore ***@***.***> Emne: Sv: [knutaa/apicore] Optimizing SubResourceReference (Issue #1) Hi, good suggestions! For the first one, try the new property "showSubResourceProperties": false This is currently default for version 2.5.2: https://github.com/knutaa/oas2puml/packages/781389 Result like this: [cid:80cc84a6-e97d-4cbf-9d8f-f8cee573d4b2] The second suggestion is a bit more work... Br, Knut
> ________________________________ Fra: AmitBarr ***@***.***> Sendt: torsdag 3. mars 2022 16:01 Til: knutaa/apicore ***@***.***> Kopi: Subscribed ***@***.***> Emne: [knutaa/apicore] Optimizing SubResourceReference (Issue #1) Hello, I enjoy using this tool, however I find that generating diagrams with more then 20 entities can make the diagram hard to read. I use the "subResourceConfig" to generate more SubResourceReference which create successful results. However I think that the next suggestions can make the diagram more optimized: 1. Allow having configuration to generate every SubResourceReference the without any properties, users can view the SubResourceReference properties on the SubResource own diagram. 2. "subResourceConfig" is not working for entitles which are not "isolated" and are pointing to an entity which has other entities pointing to it. Example A is pointing to B & C and B is pointing to C. If i added B to subResourceConfig under A it will not be generated as a sub-resource as A is pointing to it. I suggest allowing B to be separated to another SubResourceReference having C included in both diagrams. Thanks a lot, Amit — Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fknutaa%2Fapicore%2Fissues%2F1&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TMOukN1uhPVcnmQsYu2DoFRwWjsAW6anvpEF2rI1xuU%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFMSDVZFSUKYNYC7LSM3J4TU6DH6JANCNFSM5P2XJFVQ&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WOMiKjYJndDdj%2BfL%2BG%2FQ0LxiMZ%2B%2B%2FvC2GFzVElyIkG8%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> Sensitivity: Internal

Thanks Knut, 

> Hi, good suggestions! For the first one, try the new property "showSubResourceProperties": false This is currently default for version 2.5.2: https://github.com/knutaa/oas2puml/packages/781389 Result like this: [cid:80cc84a6-e97d-4cbf-9d8f-f8cee573d4b2] The second suggestion is a bit more work... Br, Knut
> […](#)
> ________________________________ Fra: AmitBarr ***@***.***> Sendt: torsdag 3. mars 2022 16:01 Til: knutaa/apicore ***@***.***> Kopi: Subscribed ***@***.***> Emne: [knutaa/apicore] Optimizing SubResourceReference (Issue #1) Hello, I enjoy using this tool, however I find that generating diagrams with more then 20 entities can make the diagram hard to read. I use the "subResourceConfig" to generate more SubResourceReference which create successful results. However I think that the next suggestions can make the diagram more optimized: 1. Allow having configuration to generate every SubResourceReference the without any properties, users can view the SubResourceReference properties on the SubResource own diagram. 2. "subResourceConfig" is not working for entitles which are not "isolated" and are pointing to an entity which has other entities pointing to it. Example A is pointing to B & C and B is pointing to C. If i added B to subResourceConfig under A it will not be generated as a sub-resource as A is pointing to it. I suggest allowing B to be separated to another SubResourceReference having C included in both diagrams. Thanks a lot, Amit — Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fknutaa%2Fapicore%2Fissues%2F1&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TMOukN1uhPVcnmQsYu2DoFRwWjsAW6anvpEF2rI1xuU%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFMSDVZFSUKYNYC7LSM3J4TU6DH6JANCNFSM5P2XJFVQ&data=04%7C01%7Cknut.johannessen%40telenor.com%7Cd9028cf081014a0d859e08d9fd26da23%7C1676489c5c7246b7ba639ab90c4aad44%7C1%7C0%7C637819165575456738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WOMiKjYJndDdj%2BfL%2BG%2FQ0LxiMZ%2B%2B%2FvC2GFzVElyIkG8%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> Sensitivity: Internal

Thanks Knut, I checked it again with the latest version and the problem didn't appear. have a good week. Amit
